fastlane_version "1.95.0"

default_platform :ios

platform :ios do

  before_all do
    sh("ls -a")
    sh("git status")
    ensure_git_status_clean
  end

  desc "Run all the tests"
  lane :test do
    scan
  end

end